config/routes.rb
Rails.application.routes.draw do
  resources :checkmusicalprods do
    collection do
      post 'verify'
    end
  end
  resources :checkartists do
    collection do
      post 'verify'
    end
  end
  get 'asso/index'
  get "lassociation.php", to: 'asso#index'
  get "compositeurs.php", to: 'compositeurs#index', as: :tous_composers
  get "compositeur.php", to: 'compositeurs#show'
  get "moncompositeur.php", to: 'compositeurs#moncompositeur'
  post "moncompositeur.php", to: 'compositeurs#ajoutermoncompositeur'
  get "realisateurs.php", to: 'realisateurs#index'
  get "realisateur.php", to: 'realisateurs#show'
  resources :comments
  get "top.php", to:'tops#index'
  get 'artists/show'
  get "/artiste.php", to: "artists#show"
  get "/recherche.php", to: "artists#recherche"
  get "/artistes.php", to: "artists#index"
  post "fetch-artistes-style.php", to: "artists#artiststyle"
  post "fetch-artistes-letters.php", to: "artists#artistletters"
  get "/top/nouveautes", to: "tops#nouveautes"
  get "/videos.php", to: "clips#showclip"
  get "/lien.php", to: "clips#lien"
  get "/autrelien.php", to: "clips#autrelien"
  get "/autrelien1.php", to: "clips#autrelien1"
  get "/checkartist.php", to: "clips#checkartist"
  get "/checkmuzicalprod.php", to: "clips#checkmuzikalprod"
  get "/checkmuzicalprodcountry.php", to: "clips#checkmuzikalprodcountry"
  get "/my_trending_videos.php", to: "clips#my_trending_videos"

  get "/top/videos/:title.html", to: "clips#showclip", as: :linktovideo
  get "/my_favorite_videos.php", to: "clips#my_fav_videos"
  get "/my_fav_jobs", to: "clips#my_fav_jobs"
  scope(:path_names => { :new => "nouveau", :edit => "editer" }) do
  resources :news, :path => "actualites"
end
    get "recover.php", to: "ajouter#user"
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :news
  resources :posts
  resources :clips
  get 'ajouter/clip'
  get "ajouter.php", to: 'ajouter#clip'
  post "ajouter.php", to: 'clips#create'
  get 'welcome/index'
  get "index.php", to: 'welcome#index'
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/clip.rb
class Clip < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :cat
  has_and_belongs_to_many :artists, :join_table => :clipsartists
  after_validation :myfavclip
  attr_accessor :formulaire
  attr_accessor :titrevideo
  def self.nouveautes
    where("created_at > ?", (DateTime.now - 4.month).beginning_of_month).order(sortie: :desc)
  end
  def self.find_with_vid(vid)
    where("parameterize(title) like ?",vid.parameterize)[0]
  end
  def mytitle
    #self.title=self.title.downcase.gsub("k-dilak", "k dilak")
    #self.title=self.title.downcase.gsub("•", "-")
    self.title.downcase.split("-")[1].strip.squish
  rescue
    self.titrevideo
  end
  def myfavclip

    if title.length > 0
      #self.title=self.title.downcase.gsub("k-dilak", "k dilak")
      #self.title=self.title.downcase.gsub("•", "-")
      self.artists = [Artist.find_or_initialize_by(name: self.titrevideo.split("-")[0].strip.squish)]
    end
    
  end
    
  has_many :views, dependent: :destroy

  def nbsemtop
    View.mysqlmyid(id)["nbsem_top"]
  rescue
    "0"
  end
  def meilleurepos
    View.mysqlmyid(id)["ma_mailleure_position"]
  rescue
    ""
  end
  def positionsemderniere
    View.mysqlmyid(id)["ifnull(ce_classement_semaine_derniere2,0)"]
  rescue
    "New"
  end
  def title=(x)
    write_attribute(:title, x.gsub("Official Video","").gsub("(Official Music Video)","").gsub("(clip officiel)","").gsub("(Clip officiel)","").strip.squish)
  end
  def title
    read_attribute(:title)
  end
  def fcat=(x)
    write_attribute(:cat_id, x)
  end
  def ytube=(x)
    write_attribute(:link, x)
  end
  def femail=(x)
    write_attribute(:email, x)
  end
  def freg=(x)
    write_attribute(:region, x)
  end
  before_validation :myfunc
  def myfunc
    videos = Yt::Collections::Videos.new
    if self.formulaire == "bonjour"
      self.title= videos.where(id: self.link+',invalid').map(&:title)[0] #pour formulaire
    end
    self.title = self.titrevideo
    self.description= videos.where(id: self.link+',invalid').map(&:description)[0]
    self.sortie= videos.where(id: self.link+',invalid').map(&:published_at)[0].to_date
    thumb=VideoThumb::get("http://www.youtube.com/watch?v=#{self.link}", "medium")
    self.image=thumb
    #system("(cd '#{Rails.root.to_s}/public/uploads' && wget '#{thumb}')")
  end
  def self.entree_dans_le_top
    self.joins(:views).order(created_at: :desc).select("clips.*, count(views.id) as countview").group("clips.id").having("count(views.id) > 0").limit(4)
  end
  def self.le_top
    self.joins(:views).select("clips.*, (select count(views.id) as countview from views group by views.clip_id, strftime('%W',views.created_at) having views.clip_id = clips.id order by countview desc,strftime('%W',views.created_at) desc limit 1) as countviews").group("clips.id").limit(3)
  end
  def myartist
      
    self.titrevideo ? self.titrevideo.split("-")[0].strip.squish : self.artists[0].name
  end
end

app/controllers/clips_controller.rb
require 'open-uri'
require 'nokogiri'
class ClipsController < ApplicationController
  before_action :set_clip, only: %i[ show edit update destroy ]

  # GET /clips or /clips.json
  def index
    @clips = Clip.all
  end

  # GET /clips/1 or /clips/1.json
  def showclip
    @clip = Clip.find_with_vid((params[:vid]||params[:title]))

    render :show
  end
 def lien
    @results=`ruby searchlinkbing.rb "#{params[:artist]}" "#{params[:title]}"`
    @results+=`python3 findvideosartist.py "#{params[:artist].downcase}" "#{params[:title].downcase}"`

 end



  
  def checkmuzikalprodcountry
    a=`ruby musikalprodcountry.rb "#{params[:country]}" "#{params[:facebook]}"`
    p "===="
    p a
    p "===="
    @results=JSON.generate(JSON.parse(a))
    p @results
    render :checkmuzikalprod
  end
  def checkmuzikalprod
    a=`ruby musikalprod.rb`
    p "===="
    p a
    p "===="
    @results=JSON.generate(JSON.parse(a))
    p @results
  end
  def my_fav_jobs
    @results=`python3 findvideosjobs.py "#{params[:country].downcase}" "#{params[:jobs].downcase}"`
    p @results
  end
  def my_fav_videos
    @results=`python3 findvideos.py "#{params[:country].downcase}"`
    p @results
  end
  def checkartist
    @results=JSON.generate(JSON.parse(`ruby labelwikipediabing.rb`))
    p @results
  end
  def artist_origin(artist_name)
    url = "https://fr.wikipedia.org/wiki/#{artist_name.gsub(' ', '_')}"
    
    begin
      page = Nokogiri::HTML(URI.open(url))
  
      # Trouver l'infobox
      infobox = page.css('.infobox_v3')
  
      artist_info = {}
      artist_info[:nom] = infobox.css('.entete div').text.strip
      artist_info[:image_url] = infobox.css('.images img').attr('src').value
      artist_info[:naissance] = page.css('th:contains("Naissance") + td').text.strip
      artist_info[:origine] = page.text.downcase.include?("Genre musical") && (page.text.downcase.include?("martinique") || page.text.downcase.include?("guadeloupe") || page.text.downcase.include?("guyane"))
  
      return artist_info[:origine]
    rescue
      return false
    end
  end
  def extract_artists_title(video_title)
    return ["Inconnu"], "Titre inconnu" if video_title.strip.empty?
  
    artists_title = video_title.split(/[-,&]/).map(&:strip)
    return ["Inconnu"], video_title if artists_title.size < 2
  
    artists = artists_title[0..-2] # Tous sauf le dernier élément
    title = artists_title[-1] # Dernier élément = titre
  
    return artists, title
  end

  
  
  def my_trending_videos
    region = { "FR" => "France" }
    @results = ""
  
    region.each do |code, name|
      videos = Yt::Collections::Videos.new
      trending = videos.where(chart: 'mostPopular', regionCode: code, categoryId: '10')
      results = ""
  
      trending.each do |video|
        artists, title = self.extract_artists_title(video.title)
        if artists.any?{|artist|artist_origin(artist)}
          results << "<p>Title: #{title}</p>"
          results << "<p>Artist: #{artist}</p>"
          results << "<p>URL: #{video.id}</p>"
          results << "<a href=\"/ajouter.php?lienvid=#{video.id}&titre=#{video.title.gsub('#','').gsub('(','').gsub(')','').gsub(' - YouTube','').gsub(' ','%20')}\">ajouter à hit lokal</a>"
          results << "<hr>"
        end
      end
      results

      @results << "<h2>Tendances en #{name}</h2>"
      @results << results
    end
  end

 def autrelien1
    @results=`ruby classement.rb`
 end
 def autrelien

    video = Yt::Video.new id: params[:channel1]
    channel = Yt::Channel.new id: video.channel_id 
    @results=""
    channel.videos.take(300).each do |vid|
      @results << "<p>Title: #{vid.title}</p>"
      @results << "<p>URL: #{vid.id}</p>"

      @results << "<a href=\"/ajouter.php?lienvid=#{vid.id}&titre=#{vid.title.gsub("#","").gsub("(","").gsub(")","").gsub(" - YouTube","").gsub(" ","%20")}\">ajouter à hit lokal</a>"
      @results << "<hr>"
    end


 end
  def show
    View.create(clip_id: @clip.id)
  end

  # GET /clips/new
  def new
    @clip = Clip.new
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips or /clips.json
  def create
    @clip = Clip.new(clip_params)

    respond_to do |format|
      if @clip.save
        format.html { redirect_to clip_url(@clip), notice: "Clip was successfully created." }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1 or /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to clip_url(@clip), notice: "Clip was successfully updated." }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1 or /clips/1.json
  def destroy
    @clip.destroy

    respond_to do |format|
      format.html { redirect_to clips_url, notice: "Clip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clip
      @clip = Clip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clip_params
      params.permit(:titrevideo,:formulaire,:fcat, :ytube, :femail, :freg, :video,:user_id)
    end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_clip.html.erb
<div id="<%= dom_id clip %>">
  <p>
    <strong>Cat:</strong>
    <%= clip.cat_id %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= clip.link %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= clip.email %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= clip.region %>
  </p>

  <p>
    <strong>Video:</strong>
    <%= clip.video %>
  </p>

</div>

app/views/clips/_form.html.erb
<%= form_with(model: clip) do |form| %>
  <% if clip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
        <% clip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cat_id, style: "display: block" %>
    <%= form.number_field :cat_id %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :region, style: "display: block" %>
    <%= form.text_field :region %>
  </div>

  <div>
    <%= form.label :video, style: "display: block" %>
    <%= form.check_box :video %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clips/autrelien.html.erb
<%=simple_format(@results).html_safe%>

app/views/clips/autrelien1.html.erb
<%=simple_format(@results).html_safe%>

app/views/clips/checkartist.html.erb
<%= content_for :mycss do%>    
<style>
        .artist-card {
            border: 1px solid #ddd;
            padding: 15px;
            margin: 10px;
            border-radius: 8px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
            display: inline-block;
            text-align: center;
            width: 200px;
        }
        .button-container {
            margin-top: 10px;
        }
        button {
            padding: 8px 12px;
            margin: 5px;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }
        .yes {
            background-color: #28a745;
            color: white;
        }
        .no {
            background-color: #dc3545;
            color: white;
        }
    </style>
<%end%>
    <div id="artist-list">

</div>
<button id="renderartist" onclick="renderArtists();return false;">render artists</button>
<script>
        const artists = JSON.parse(<%= @results.to_json.html_safe %>);
        console.log(artists);
        function renderArtists() {
            const artistList = document.getElementById("artist-list");
            artistList.innerHTML = "";

            artists.artists.forEach(artist => {
                const card = document.createElement("div");
                card.className = "artist-card";
                card.innerHTML = `<h3>${artist.name}</h3><p>${artist.country}</p>
                    <div class="button-container">
                        <button class="yes" onclick="sendResponse('${artist.name}', '${artist.country}', true)">Yes</button>
                        <button class="no" onclick="sendResponse('${artist.name}', '${artist.country}', false)">No</button>
                    </div>`;
                artistList.appendChild(card);
            });
        }

        function sendResponse(name, country, isArtist) {
            const query = new URLSearchParams({ name, country, isArtist }).toString();
            const url = `/checkartists/verify?${query}`;

            fetch(url, { method: "POST" })
                .then(response => response.json())
                .then(data => console.log("Server response:", data))
                .catch(error => console.error("Error:", error));
        }

        renderArtists();
    </script>

app/views/clips/checkmuzikalprod.html.erb
<%= content_for :mycss do%>    
<style>
        .musicalprod-card {
            border: 1px solid #ddd;
            padding: 15px;
            margin: 10px;
            border-radius: 8px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
            display: inline-block;
            text-align: center;
            width: 200px;
        }
        .button-container {
            margin-top: 10px;
        }
        button {
            padding: 8px 12px;
            margin: 5px;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }
        .yes {
            background-color: #28a745;
            color: white;
        }
        .no {
            background-color: #dc3545;
            color: white;
        }
    </style>
<%end%>
    <div id="musicalprod-list">

</div>
<button id="renderartist" onclick="renderMusicalprods();return false;">render artists</button>

<script>


        function renderMusicalprods() {
            var musicalprods = JSON.parse(<%= @results.to_json.html_safe %>);
            console.log(musicalprods);
            const musicalprodList = document.getElementById("musicalprod-list");
            musicalprodList.innerHTML = "";

            musicalprods.musicalprods.forEach(musicalprod => {
                const card = document.createElement("div");
                card.className = "musicalprod-card";
                card.innerHTML = `<h3>${musicalprod.name}</h3><p>${musicalprod.country}</p>
                    <div class="button-container">
                        <button class="yes" onclick="sendResponse('${musicalprod.name}', '${musicalprod.country}', true)">Yes</button>
                        <button class="no" onclick="sendResponse('${musicalprod.name}', '${musicalprod.country}', false)">No</button>
                    </div>`;
                musicalprodList.appendChild(card);
            });
        }

        function sendResponse(name, country, isMusicalprod) {
            const query = new URLSearchParams({ name, country, isMusicalprod }).toString();
            const url = `/checkmusicalprods/verify?${query}`;

            fetch(url, { method: "POST" })
                .then(response => response.json())
                .then(data => console.log("Server response:", data))
                .catch(error => console.error("Error:", error));
        }

window.onload=function(){
        renderMusicalprods();
}
    </script>

app/views/clips/edit.html.erb
<h1>Editing clip</h1>

<%= render "form", clip: @clip %>

<br>

<div>
  <%= link_to "Show this clip", @clip %> |
  <%= link_to "Back to clips", clips_path %>
</div>

app/views/clips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clips</h1>

<div id="clips">
  <% @clips.each do |clip| %>
    <%= render clip %>
    <p>
      <%= link_to "Show this clip", clip %>
    </p>
  <% end %>
</div>

<%= link_to "New clip", new_clip_path %>

app/views/clips/lien.html.erb
 <li>Un lien Youtube</li>
                          <li>
<%= form_tag '/lien.php', method: :get do %>
<%= label_tag :artist, 'Artist' %>
<%= text_field_tag :artist, params[:artist] %>

<%= label_tag :title, 'Title' %>
<%= text_field_tag :title, params[:title] %>

<%= submit_tag 'Submit' %>
<% end %>


</li>


<%=simple_format(@results).html_safe%>

app/views/clips/my_trending_videos.html.erb
<%=simple_format(@results).html_safe%>

app/views/clips/new.html.erb
<h1>New clip</h1>

<%= render "form", clip: @clip %>

<br>

<div>
  <%= link_to "Back to clips", clips_path %>
</div>

app/views/clips/show.html.erb
<%=content_for :titlesong do%>
                      <%@clip.artists.each do |artist|%>
                          <%=artist.name%>                          <%end%> - <%=@clip.mytitle%> - 
  <%end%>

<p style="color: green"><%= notice %></p>


	<div id="artistes-1" class="details-1 bg-gray position-relative" data-id="9471">
		<div class="container">
            <div class="row">
                <div class="col-lg-12">
				    <div style="display: flex; margin-top: 30px;">
					 <br />
					 <br />
					                     <h2 style="width: 50%; text-align: leftt;"class="h2-heading-details"  style="z-index:2">
                      <%@clip.artists.each do |artist|%><a href="/artiste.php?ar=<%=artist.id%>" title="<%=@clip.title%>">
                          <%=artist.name%>                          </a><%end%> <%=@clip.mytitle%></h2>
                     <h3 style="width: 40%; text-align: right; color:gold"><i class="fa fa-eye" aria-hidden="true"></i><%=t("monclip.vue",count: @clip.views.length)%></h3>
					<br />
					 <br />
					</div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
                <div class="col-lg-12">
                    <div class="row">

                    <div class="video-responsive">
                   	<iframe width="80%" height="548" src="https://www.youtube.com/embed/<%=@clip.link%>?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
					</div>

                </div> <!-- end of col -->
            </div> <!-- end of row -->


								<div class="text-3">
					Partager
					</div>
					<!-- Facebook -->
                       	   <button style="background:transparent!important; border:0!important" class="button" data-sharer="facebook" data-title="hit-lokal!" data-hashtag="hitlokal" data-url="https://hit-lokal.com/videos.php?vid=<%=@clip.title.parameterize%>">
			        <i class="fab fa-facebook-f" style="background: #ffd800;  padding: 15px 20px; font-size: 25px; border-radius: 100%; color: #FFF"></i>
			         </button>
                    <!-- Facebook -->

					<!-- Twitter -->
                    <button style="background:transparent!important; border:0!important" class="button" data-sharer="twitter" data-title="hit-lokal!" data-hashtags="hitlokal" data-url="https://hit-lokal.com/videos.php?vid=lizi-loverdose">
				     <i class="fab fa-twitter" style="background: #ffd800;    padding: 15px; font-size: 25px; border-radius: 100%; color: #FFF"></i>
				    </button>
					<!-- Twitter -->




			    <div class="col-lg-8  offset-lg-2">
                    <div class="row" style="margin-top: 30px">

              			   <div class="entry-post" style="white-space: pre-wrap;">
                      
<%=simple_format(@clip.description.html_safe)%>
					</div>
                    

					  <div class="col-lg-8  offset-lg-2">
                    <div class="row" style="margin-top: 30px; margin-bottom: 30px">

                                              </div>
                    </div>


                  <table class="table">
                    <th colspan="6">A propos de <%=@clip.title%></th>

                    <tr>
                      <td>Titre</td>
                      <td><%=@clip.title%></td>

                      <td class="break">Artiste(s)</td>
                        <%@clip.artists.each do |x|%>
                       <td><a href="artiste.php?ar=<%=x.id%>"><%=x.name%></a></p></td>
                        <%end%>
                    </tr>
                    <tr>
                      <td class="break">Catégorie(s)</td>
                      <td><%=@clip.cat.name%></p></td>

                      <td class="break">Sortie le</td>
                      <td><%=l(@clip.sortie)%></td>
                    </tr>

                  </table>

                  <div class="table-responsive">
                  <table class="table table-condensed">

                    <th colspan="6">Statistiques de <%=@clip.title%></th>

                    <tr>
                      <td>Meilleure position</td>
                      <td><span class="label label-stat" title="Meilleur position dans le top"><i class="fa fa-trophy fa-1x"></i> <%=@clip.meilleurepos%></span>&nbsp;</td>

                      <td  class="break">Position la semaine dernière</td>
                      <td >
                        <span class="label label-stat" title="Position la semaine dernière"><i class="fa fa-caret-square-left fa-1x"></i> <%=@clip.positionsemderniere||"New"%></span>&nbsp;
                      </td>

                      <td class="break">Nbr semaine dans le top</td>
                      <td><span class="label label-stat" title="Nombre de semaines dans le top"><i class="fa fa-clock" aria-hidden="true"></i> <%=@clip.nbsemtop%></i></span></td>
                    </tr>

                  </table>
				  </div>



				        </div> <!-- end of col -->
            </div> <!-- end of row -->


		</div> <!-- end of container -->
    </div> <!-- end of filter -->
    <!-- end of top artistes -->
<div id="artistes-2" class="details-2 bg-gray position-relative">
		<div class="container">
		            <div class="row">
                <div class="col-lg-12">
				    <div style="display: flex">
                    <h2 class="h2-heading-details"  style="z-index:2">Vous pourriez aussi aimer</h2>
					</div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
                <div class="col-lg-12">
                    <div class="row">
					                        <div class="element-item col-lg-2"  style="z-index:2">
                             <a href="../../videos.php?vid=lizi-loverdose" title="Lizi - loverdose">
                              <img class="img-fluid"  src="../../media/clip/2023/07/lizi-loverdose-clip-officiel-2023.jpg" alt="Lizi - loverdose">
								<div class="artistes-2-content">Lizi</div>
                            </a>
                        </div>
					                            <div class="element-item col-lg-2"  style="z-index:2">
                             <a href="../../videos.php?vid=jooslyf-x-mata-feux-dla-mort" title="Jooslyf x mata - Feux d'la mort">
                              <img class="img-fluid"  src="../../media/clip/2023/07/jooslyf-x-mata-feux-dla-mort-2023.jpg" alt="Jooslyf x mata - Feux d'la mort">
								<div class="artistes-2-content">Jooslyf x mata</div>
                            </a>
                        </div>
					                            <div class="element-item col-lg-2"  style="z-index:2">
                             <a href="../../videos.php?vid=cecinelle-pa-taw" title="Cécinelle - Pa taw">
                              <img class="img-fluid"  src="../../media/clip/2023/07/cecinelle-pa-taw-clip-officiel--2023.jpg" alt="Cécinelle - Pa taw">
								<div class="artistes-2-content">Cécinelle</div>
                            </a>
                        </div>
					                            <div class="element-item col-lg-2"  style="z-index:2">
                             <a href="../../videos.php?vid=killi-x-lydogg-lari" title="Killi x Lydogg - Lari">
                              <img class="img-fluid"  src="../../media/clip/2023/07/killi-x-lydogg-lari-2kartel-films-2023.jpg" alt="Killi x Lydogg - Lari">
								<div class="artistes-2-content">Killi x Lydogg</div>
                            </a>
                        </div>
					                            <div class="element-item col-lg-2"  style="z-index:2">
                             <a href="../../videos.php?vid=walton-clr-x-rodias-patience" title="Walton clr x Rodias - Patience">
                              <img class="img-fluid"  src="../../media/clip/2023/07/walton-clr-x-rodias-patience-2023.jpg" alt="Walton clr x Rodias - Patience">
								<div class="artistes-2-content">Walton clr x Rodias</div>
                            </a>
                        </div>
					                    </div> <!-- end of col -->
            </div> <!-- end of row -->
		</div> <!-- end of container -->
    </div> <!-- end of filter -->
    <!-- end of top artistes -->



<div>
  <%= link_to "Edit this clip", edit_clip_path(@clip) %> |
  <%= link_to "Back to clips", clips_path %>

  <%= button_to "Destroy this clip", @clip, method: :delete %>
</div>