config/routes.rb
Rails.application.routes.draw do
  resources :checkmusicalprods do
    collection do
      post 'verify'
    end
  end
  resources :checkartists do
    collection do
      post 'verify'
    end
  end
  get 'asso/index'
  get "lassociation.php", to: 'asso#index'
  get "compositeurs.php", to: 'compositeurs#index', as: :tous_composers
  get "compositeur.php", to: 'compositeurs#show'
  get "moncompositeur.php", to: 'compositeurs#moncompositeur'
  post "moncompositeur.php", to: 'compositeurs#ajoutermoncompositeur'
  get "realisateurs.php", to: 'realisateurs#index'
  get "realisateur.php", to: 'realisateurs#show'
  resources :comments
  get "top.php", to:'tops#index'
  get 'artists/show'
  get "/artiste.php", to: "artists#show"
  get "/recherche.php", to: "artists#recherche"
  get "/artistes.php", to: "artists#index"
  post "fetch-artistes-style.php", to: "artists#artiststyle"
  post "fetch-artistes-letters.php", to: "artists#artistletters"
  get "/top/nouveautes", to: "tops#nouveautes"
  get "/videos.php", to: "clips#showclip"
  get "/lien.php", to: "clips#lien"
  get "/autrelien.php", to: "clips#autrelien"
  get "/autrelien1.php", to: "clips#autrelien1"
  get "/checkartist.php", to: "clips#checkartist"
  get "/checkmuzicalprod.php", to: "clips#checkmuzikalprod"
  get "/checkmuzicalprodcountry.php", to: "clips#checkmuzikalprodcountry"
  get "/my_trending_videos.php", to: "clips#my_trending_videos"

  get "/top/videos/:title.html", to: "clips#showclip", as: :linktovideo
  get "/my_favorite_videos.php", to: "clips#my_fav_videos"
  get "/my_fav_jobs", to: "clips#my_fav_jobs"
  scope(:path_names => { :new => "nouveau", :edit => "editer" }) do
  resources :news, :path => "actualites"
end
    get "recover.php", to: "ajouter#user"
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :news
  resources :posts
  resources :clips
  get 'ajouter/clip'
  get "ajouter.php", to: 'ajouter#clip'
  post "ajouter.php", to: 'clips#create'
  get 'welcome/index'
  get "index.php", to: 'welcome#index'
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/news.rb
class News < ApplicationRecord
belongs_to :user
has_many :views, class_name: "Viewnews"
has_many :comments
	def resumearticle
          content
        end

def self.mostrecent
self.order(created_at: :desc).limit(1)[0]
end
def lastnew
News.all.where.not(id: self.id).order(created_at: :desc).limit(4)
end
def othernew(lastnew)
News.all.joins(:views).select("news.*, count(viewnews.id) as countview").group("news.id").having(["news.id <> ?", self.id]).order("countview" => "desc").offset(4).limit(4)
end
  def self.findnews(vid)
    where("parameterize(title) like ?",vid.parameterize)[0]
  end

def self.mostrecentnews
self.order(created_at: :desc).limit(1)
end
def self.mymostrecentnews
self.order(created_at: :desc).limit(6)
end
def image
read_attribute(:image)
end
def image=(uploaded_io)
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
write_attribute(:image,uploaded_io.original_filename)
end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ edit update destroy ]
  before_action :set_my_news, only: %i[ show ]
before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /news or /news.json
  def index
    @news = News.all.mostrecent
    render :show
    Viewnews.create(news_id: @news.id)
    @lastnew=@news.lastnew
    @othernew=@news.othernew(@lastnew)
  end

  # GET /news/1 or /news/1.json
  def show
Viewnews.create(news_id: @news.id)
@lastnew=@news.lastnew
@othernew=@news.othernew(@lastnew)
  end

  # GET /news/new
  def new
    @news = News.new(user_id: current_user.try(:id))
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news.title.parameterize), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news.title.parameterize), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end
    def set_my_news
      @news = News.findnews(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :user_id, :content, :image)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

    <%= form.hidden_field :user_id, style: "display: block" %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_lastnew.html.erb
<div class="image-container" style="position:relative; z-index:1;  font-size: 14px;" >

                         <a href="/actualites/<%=news.title.parameterize%>" title="<%=news.title%>">
                                                    <img src="/uploads/<%=news.image%>" alt="<%=news.title%>"

                                                 style="width: 300px;
                                                                height: 200px;
                                                                background: #C4C4C4;"
                                                />
                                                </a>
                                                 <div style="max-width: 300px;"><b><%=news.title%></b></div>
                     </div> <!-- end of col -->
                     <br />

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Title:</strong>
    <%= news.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= news.user_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= news.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= news.image %>
  </p>

</div>

app/views/news/_othernew.html.erb
<div class="element-item col-lg-3">
                        <a href="/actualites/<%=news.title.parameterize%>" title="<%=news.title%>">
                            <img style="width: 300px;   height: 200px;  background: #C4C4C4;" src="/uploads/<%=news.image%>" alt="<%=news.title%>">
                            <div class="">
                            <!--        <button class="btn-solid-green">Artiste</button>  -->
                                <span class="actu-date" >Publié à <%=l(news.created_at, format: :publie)%></span>
                            </div>

                            <div class="actu-content"><%=news.title%></div>
                        </a>
                    </div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Show this news", @news %> |
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>News</h1>

<div id="news">
  <% @news.each do |news| %>
    <%= render news %>
    <p>
      <%= link_to "Show this news", news %>
    </p>
  <% end %>
</div>

<%= link_to "New news", new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<style>
iframe {
    border: 0!important;
    max-width: 100%!important;
}

.img-h{
    height: 450px;
    margin: auto;
    background: #C4C4C4;
}

@media only screen and (max-width: 600px) {
    .img-h{
    height: auto;
    margin: auto;
    background: #C4C4C4;
    }
}
</style>
    <div id="actu-1" class="basic-2 position-relative actu-1"  style="z-index:2">
        <span style="display: none">
                    </span>
		<div class="vecteur-8" ></div>
        <div class="container">
		            <div class="row">
                <div class="col-lg-12">
				    <div style="display: flex">
                    <h2 class="h2-heading">Les actus </h2><span class="line-2" ></span>
					</div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
            <div class="row container-p1 actu-m">


                <div class="col-lg-8 col-xs-12 ">
                    <h1 style="font-size:32px"><%=@news.title%></h1>

				  <!--   <button class="btn-solid-green">Artiste</button> -->
				     <div class="text-1">Ecrit par <%=@news.user.username%> le <%=l(@news.created_at.to_date)%> - <span style="font-weight:600; color: black; margin-left:5px">  <%=t("monclip.vue",count:@news.views.length)%></span></div>
                    <hr />
                    <div style="display: flex; justify-content: space-around;     margin-top: -10px; line-height: 3;">
                    <div class="text-3">
					Partager
					</div>
					<div>
					<!-- Facebook -->

                     <button style="background:transparent!important; border:0!important" class="button" data-sharer="facebook" data-title="hit-lokal!" data-hashtag="hitlokal" data-url="https://hit-lokal.com/actualites/<%=@news.title.parameterize%>">
			        <i class="fab fa-facebook-f" style="background: #ffd800;  padding: 10px 15px; font-size: 25px; border-radius: 100%; color: #FFF"></i>
			         </button>

                    <!-- Facebook -->

					<!-- Twitter -->
                    <button style="background:transparent!important; border:0!important" class="button" data-sharer="twitter" data-title="hit-lokal!" data-hashtags="hitlokal" data-url="https://hit-lokal.com/actualites/<%=@news.title.parameterize%>">
				     <i class="fab fa-twitter" style="background: #ffd800;    padding: 10px; font-size: 25px; border-radius: 100%; color: #FFF"></i>
				    </button>
					<!-- Twitter -->
					</div>
                    </div>
                     <div class="image-container" style="position:relative; z-index:1" >
                        <img class="img-fluid img-h" src="<%=@news.image%>"
                            alt="<%=@news.title%>"
						/>
                     </div> <!-- end of col -->
					 <div class="col-lg-8 text-2" style="width: auto;" id="resumeArticle">
<%=strip_tags(@news.content.to_s)[0..124]%>                    </div> <!-- end of text-container -->

                       <div style="float: right; cursor: pointer; color: black" id="viewAll" onclick="document.getElementById('resumeArticle').style.display='none';document.getElementById('viewAll').style.display='none';document.getElementById('allArticle').style.display='block';document.getElementById('viewAll').style.display='none';">Lire tout l'article</div>
                        <br />
	                <div class="col-lg-8 text-2" style="width: auto; display: none" id="allArticle" >

<%=simple_format(@news.content).html_safe%>
                    <hr />
                    <div style="display: flex; justify-content: space-around;     margin-top: -10px; line-height: 3;">
                    <div class="text-3">
					Partager
					</div>
					<div>
					<!-- Facebook -->
                       	   <button style="background:transparent!important; border:0!important" class="button" data-sharer="facebook" data-title="hit-lokal!" data-hashtag="hitlokal" data-url="https://hit-lokal.com//actualites/<%=@news.title.parameterize%>">
			        <i class="fab fa-facebook-f" style="background: #ffd800;  padding: 10px 15px; font-size: 25px; border-radius: 100%; color: #FFF"></i>
			         </button>
                    <!-- Facebook -->
					<!-- Twitter -->
                    <button style="background:transparent!important; border:0!important" class="button" data-sharer="twitter" data-title="hit-lokal!" data-hashtags="hitlokal" data-url="https://hit-lokal.com//actualites/<%=@news.title.parameterize%>">
				     <i class="fab fa-twitter" style="background: #ffd800;    padding: 10px; font-size: 25px; border-radius: 100%; color: #FFF"></i>
				    </button>
					<!-- Twitter -->
					</div>
                    </div>

                    <div class="text-3 text-4">
					    Commentaires (<%=@news.comments.length%>)
					</div>
					    <%=render @news.comments%>)

										<form id="mymsg" action="/comments" method="post">
                        <div class="form-group">
                            <%if !user_signed_in?%>Vous devez être connecté(e) pour laisser un commentaire.<%end%>                            <textarea name="comment[content]" class="form-control-textarea" placeholder="Message" required <%if !user_signed_in?%>disabled<%end%> ></textarea>
<%if user_signed_in?%>
<input type="hidden" name="comment[user_id]" value="<%=current_user.id%>"/>
<input type="hidden" name="comment[news_id]" value="<%=@news.id%>"/>
<button type="submit">envoyer</button>
<%end%>

                        </div>
                    </form>
                    </div>
				</div>
			    <div class="col-lg-4 col-xs-12">
                    <h2 style="background: #272727;
                                font-size: 14px;
                                font-weight: 500;
                                text-transform: uppercase;
                                margin: 0 0 15px;
                                color: #fff;
                                text-align: center;
                                max-width: 300px;">
                        Dernières actualités</h2>
<%=render partial: "news/lastnew", collection: @lastnew, as: :news%>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of basic-1 -->
    <!-- end of details 1 -->


<!-- --- -->
<!-- --- -->
<!-- actu-2 -->
<!-- --- -->
<!-- --- -->
	<div id="actu-2" class="basic-2  bg-gray position-relative" style="z-index:2">
		<div class="container">
            <div class="row">
                <div class="col-lg-12">
				    <div style="display: flex">
                    <h2 class="h2-heading">Encore plus d'actus à découvrir </h2><span class="line-2" ></span>
					</div>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
			<div class="container">
					 <div class="col-lg-12">
            <div class=" actu-2 row">
                                <!--
<%=render collection: @othernew, as: :news, partial: "news/othernew"%>
                    <button class="btn-solid-red">Album</button>
                    <button class="btn-solid-yellow">Awards</button>

                    <button class="btn-solid-brown">Release</button>
                    -->
                <!-- end of filter -->
                </div> <!-- end of col -->
            </div>
            </div> <!-- end of row -->
		</div> <!-- end of container -->
    </div> <!-- end of filter -->
    <!-- end of sorties -->

<div>
  <%= link_to "Edit this news", edit_news_path(@news) %> |
  <%= link_to "Back to news", news_index_path %>

  <%= button_to "Destroy this news", @news, method: :delete %>
</div>